require: rubocop-sketchup

inherit_from:
  - https://raw.githubusercontent.com/SketchUp/rubocop-sketchup/be63d4cf143b0d7cd4d517804efc9a5850802b24/sketchup-style.yml

AllCops:
  DisabledByDefault: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - src/*/vendor/**/*
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2014
    Exclude:
      - Research/**/*
      - skippy/**/*
      - Tests/**/*
  TargetRubyVersion: 2.0


Layout/EmptyLineBetweenDefs:
  Exclude:
  - src/tt_solid_inspector2/settings.rb
  - src/tt_solid_inspector2/inspector_tool.rb

# TODO:
Layout/FirstArgumentIndentation:
  Enabled: false

# TODO:
Layout/HashAlignment:
  Enabled: false


Metrics/MethodLength:
  Max: 30
  Enabled: false # TODO


Naming/ClassAndModuleCamelCase:
  Exclude:
    - src/tt_solid_inspector2/gl/**/*
    - src/tt_solid_inspector2/gl_*
    - Tests/**/*

Naming/FileName:
  Exclude:
    - Tests/**/*

Naming/MethodName:
  Exclude:
    - src/tt_solid_inspector2/core.rb
    - src/tt_solid_inspector2/debug_tools.rb
    - src/tt_solid_inspector2/inspector_tool.rb
    - Tests/**/*

# TODO: Add these to sketchup-style.yml
Naming/MethodParameterName:
  AllowedNames:
  - id
  - x
  - y
  - z
  - u
  - v


# TODO: Use autofix on this
Style/StringLiterals:
  Enabled: false

# TODO:
Style/TrailingCommaInArrayLiteral:
  Enabled: false

# TODO:
Style/TrailingCommaInHashLiteral:
  Enabled: false


# Enable the cop that checks for Ruby compatibility.
# Lint/Syntax:
  # Enabled: true
