require: rubocop-sketchup

inherit_from:
  - https://raw.githubusercontent.com/SketchUp/rubocop-sketchup/be63d4cf143b0d7cd4d517804efc9a5850802b24/sketchup-style.yml

AllCops:
  DisabledByDefault: true
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - src/*/vendor/**/*
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2014
    Exclude:
      - Research/**/*
      - skippy/**/*
      - Tests/**/*
  TargetRubyVersion: 2.0


Naming/ClassAndModuleCamelCase:
  Exclude:
    - Tests/**/*

Naming/FileName:
  Exclude:
    - Tests/**/*

Naming/MethodName:
  Exclude:
    - Tests/**/*

# TODO: Add these to sketchup-style.yml
# Naming/UncommunicativeMethodParamName:
#   AllowedNames:
#     - x
#     - y
#     - z
#     - u
#     - v

# TODO: Use autofix on this
Style/StringLiterals:
  Enabled: false
